/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animated;

/**
 *
 * @author Admin
 */
public class Tictactoe extends javax.swing.JFrame {
     boolean flag;
     String p1,p2;
    public Tictactoe(String s1,String s2) {
        p1=s1;
        p2=s2;
        initComponents();
        setLayout(null);
        setLocation(400, 400);
        setSize(400, 500);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        resteB = new javax.swing.JButton();
        winner = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        oneB = new javax.swing.JButton();
        twoB = new javax.swing.JButton();
        theeeB = new javax.swing.JButton();
        fourB = new javax.swing.JButton();
        fiveB = new javax.swing.JButton();
        sixB = new javax.swing.JButton();
        sevenB = new javax.swing.JButton();
        eightB = new javax.swing.JButton();
        nineB = new javax.swing.JButton();

        jButton7.setText("jButton7");

        jButton9.setText("jButton9");

        jButton11.setText("jButton11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Tic Tac Toe !!!!");

        resteB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resteB.setText("reset");
        resteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resteBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(winner, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(resteB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resteB, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(winner)))
        );

        jPanel2.setLayout(new java.awt.GridLayout(3, 3));

        oneB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBActionPerformed(evt);
            }
        });
        jPanel2.add(oneB);

        twoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBActionPerformed(evt);
            }
        });
        jPanel2.add(twoB);

        theeeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theeeBActionPerformed(evt);
            }
        });
        jPanel2.add(theeeB);

        fourB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBActionPerformed(evt);
            }
        });
        jPanel2.add(fourB);

        fiveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBActionPerformed(evt);
            }
        });
        jPanel2.add(fiveB);

        sixB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBActionPerformed(evt);
            }
        });
        jPanel2.add(sixB);

        sevenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBActionPerformed(evt);
            }
        });
        jPanel2.add(sevenB);

        eightB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBActionPerformed(evt);
            }
        });
        jPanel2.add(eightB);

        nineB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBActionPerformed(evt);
            }
        });
        jPanel2.add(nineB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eightBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBActionPerformed
        // TODO add your handling code here:
        if(eightB.getText().equals(""))
        {
            flag=!flag;
            if(flag==true)
            {
                eightB.setText("X");
            }
            else
            {
                eightB.setText("O");
            }
        }
        check();
    }//GEN-LAST:event_eightBActionPerformed

    private void resteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resteBActionPerformed
        // TODO add your handling code here:
        oneB.setText("");
         twoB.setText("");
          theeeB.setText("");
           fourB.setText("");
            fiveB.setText("");
             sixB.setText("");
              sevenB.setText("");
               eightB.setText("");
                nineB.setText("");
                 winner.setText("");
    }//GEN-LAST:event_resteBActionPerformed

    private void oneBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBActionPerformed
        if(oneB.getText().equals(""))
        {
            flag=!flag;
            if(flag==true)
            {
                oneB.setText("X");
            }
            else
            {
                oneB.setText("O");
            }
        }  
        check();// TODO add your handling code here:
    }//GEN-LAST:event_oneBActionPerformed

    private void twoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBActionPerformed
       if(twoB.getText().equals(""))
        {
            flag=!flag;
            if(flag==true)
            {
                twoB.setText("X");
            }
            else
            {
                twoB.setText("O");
            }
        }    
       check();// TODO add your handling code here:
    }//GEN-LAST:event_twoBActionPerformed

    private void theeeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theeeBActionPerformed
       if(theeeB.getText().equals(""))
        {
            flag=!flag;
            if(flag==true)
            {
                theeeB.setText("X");
            }
            else
            {
                theeeB.setText("O");
            }
        }  
       check();// TODO add your handling code here:
    }//GEN-LAST:event_theeeBActionPerformed

    private void fourBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBActionPerformed
        if(fourB.getText().equals(""))
        {
            flag=!flag;
            if(flag==true)
            {
                fourB.setText("X");
            }
            else
            {
                fourB.setText("O");
            }
        }  
        check();// TODO add your handling code here:
    }//GEN-LAST:event_fourBActionPerformed

    private void fiveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBActionPerformed
       if(fiveB.getText().equals(""))
        {
            flag=!flag;
            if(flag==true)
            {
                fiveB.setText("X");
            }
            else
            {
                fiveB.setText("O");
            }
        }   
       check();// TODO add your handling code here:
    }//GEN-LAST:event_fiveBActionPerformed

    private void sixBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBActionPerformed
        if(sixB.getText().equals(""))
        {
            flag=!flag;
            if(flag==true)
            {
                sixB.setText("X");
            }
            else
            {
                sixB.setText("O");
            }
        } 
        check();// TODO add your handling code here:
    }//GEN-LAST:event_sixBActionPerformed

    private void sevenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBActionPerformed
        if(sevenB.getText().equals(""))
        {
            flag=!flag;
            if(flag==true)
            {
                sevenB.setText("X");
            }
            else
            {
                sevenB.setText("O");
            }
        } 
        check();// TODO add your handling code here:
    }//GEN-LAST:event_sevenBActionPerformed

    private void nineBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBActionPerformed
       if(nineB.getText().equals(""))
        {
            flag=!flag;
            if(flag==true)
            {
                nineB.setText("X");
            }
            else
            {
                nineB.setText("O");
            }
        }
       check();// TODO add your handling code here:
    }//GEN-LAST:event_nineBActionPerformed

    String getWinnername(String var)
    {
        if(var=="X")
        {
            return p1;
        }
        else
        {
            return p2;
        }
    }
    
    void check()
    {
        if(oneB.getText().equals(twoB.getText()) && theeeB.getText().equals(twoB.getText()) && !oneB.getText().equals(""))
        {
            winner.setText(getWinnername(oneB.getText()+"is winner"));
        }
      else  if(oneB.getText().equals(fourB.getText()) && sevenB.getText().equals(fourB.getText()) && !oneB.getText().equals(""))
        {
            winner.setText(getWinnername(oneB.getText()+"is winner"));
        }
     else   if(oneB.getText().equals(fiveB.getText()) && nineB.getText().equals(fiveB.getText()) && !oneB.getText().equals(""))
        {
            winner.setText(getWinnername(oneB.getText()+"is winner"));
        }
     else   if(twoB.getText().equals(fiveB.getText()) && eightB.getText().equals(fiveB.getText()) && !twoB.getText().equals(""))
        {
            winner.setText(getWinnername(twoB.getText()+"is winner"));
        }
     else   if(theeeB.getText().equals(sixB.getText()) && nineB.getText().equals(sixB.getText()) && !theeeB.getText().equals(""))
        {
            winner.setText(getWinnername(theeeB.getText()+"is winner"));
        }
      else  if(theeeB.getText().equals(fiveB.getText()) && sevenB.getText().equals(fiveB.getText()) && !theeeB.getText().equals(""))
        {
            winner.setText(getWinnername(theeeB.getText()+"is winner"));
        }
      else  if(fourB.getText().equals(fiveB.getText()) && sixB.getText().equals(fiveB.getText()) && !fourB.getText().equals(""))
        {
            winner.setText(getWinnername(fourB.getText()+"is winner"));
        }
     else   if(sevenB.getText().equals(eightB.getText()) && nineB.getText().equals(eightB.getText()) && !sevenB.getText().equals(""))
        {
            winner.setText(getWinnername(sevenB.getText()+"is winner"));
        }
    }
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eightB;
    private javax.swing.JButton fiveB;
    private javax.swing.JButton fourB;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton nineB;
    private javax.swing.JButton oneB;
    private javax.swing.JButton resteB;
    private javax.swing.JButton sevenB;
    private javax.swing.JButton sixB;
    private javax.swing.JButton theeeB;
    private javax.swing.JButton twoB;
    private javax.swing.JTextField winner;
    // End of variables declaration//GEN-END:variables
}
